//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Amigo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Passengers
    {
        public int travelId { get; set; }
        public int userId { get; set; }
        public int nbBookedSeats { get; set; }
    
        public virtual travel travel { get; set; }
        public virtual users users { get; set; }
    }
}
